version: "3.9"
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: trvl
      POSTGRES_USER: trvl
      POSTGRES_PASSWORD: trvl
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U trvl -d trvl"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  db_data:


