"""add category to backlog_cards

Revision ID: 249abd0610eb
Revises: e3c452322cbc
Create Date: 2025-09-17 11:13:56.006035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '249abd0610eb'
down_revision: Union[str, Sequence[str], None] = 'e3c452322cbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backlog_cards', sa.Column('category', sa.String(length=30), server_default='activities', nullable=False))
    # drop server default after backfill
    op.alter_column('backlog_cards', 'category', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backlog_cards', 'category')
    # ### end Alembic commands ###
