"""add_creator_to_backlog_cards

Revision ID: 5f2cd47a591b
Revises: 627f9b007ff0
Create Date: 2025-09-23 11:47:41.614194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f2cd47a591b'
down_revision: Union[str, Sequence[str], None] = '627f9b007ff0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backlog_cards', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('backlog_cards', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    
    # Set default created_at for existing records
    op.execute("UPDATE backlog_cards SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL")
    
    # Now make created_at NOT NULL
    op.alter_column('backlog_cards', 'created_at', nullable=False)
    
    op.create_foreign_key(None, 'backlog_cards', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'backlog_cards', type_='foreignkey')
    op.drop_column('backlog_cards', 'created_at')
    op.drop_column('backlog_cards', 'created_by')
    # ### end Alembic commands ###
